from app.models import db, Comment



def seed_comments():   

  like1 = Comment(user_id=1, post_id=1)
  like2 = Comment(user_id=2, post_id=2)
  like3 = Comment(user_id=3, post_id=3)
  like4 = Comment(user_id=4, post_id=4)
  like5 = Comment(user_id=5, post_id=5)
  like6 = Comment(user_id=6, post_id=6)
  like7 = Comment(user_id=7, post_id=7)
  like8 = Comment(user_id=8, post_id=8)
  like9 = Comment(user_id=1, post_id=9)
  like10 = Comment(user_id=2, post_id=10)
  like11 = Comment(user_id=3, post_id=10)
  like12 = Comment(user_id=4, post_id=11)
  like13 = Comment(user_id=5, post_id=12)
  like14 = Comment(user_id=6, post_id=12)
  like15 = Comment(user_id=7, post_id=13)
  like16 = Comment(user_id=8, post_id=14)
  like17 = Comment(user_id=1, post_id=16)
  like18 = Comment(user_id=2, post_id=17)
  like19 = Comment(user_id=3, post_id=18)
  like20 = Comment(user_id=4, post_id=19)
  like21 = Comment(user_id=5, post_id=21)
  like22 = Comment(user_id=6, post_id=23)
  like23 = Comment(user_id=7, post_id=23)
  like24 = Comment(user_id=8, post_id=24)
  like25 = Comment(user_id=1, post_id=25)
  like26 = Comment(user_id=2, post_id=26)
  like27 = Comment(user_id=3, post_id=26)
  like28 = Comment(user_id=4, post_id=28)
  like29 = Comment(user_id=5, post_id=29)
  like30 = Comment(user_id=6, post_id=30)
  like31 = Comment(user_id=7, post_id=32)
  like32 = Comment(user_id=8, post_id=32)
  like33 = Comment(user_id=1, post_id=33)
  like34 = Comment(user_id=2, post_id=34)
  like35 = Comment(user_id=3, post_id=36)
  like36 = Comment(user_id=4, post_id=36)
  like37 = Comment(user_id=5, post_id=36)
  like38 = Comment(user_id=6, post_id=38)
  like39 = Comment(user_id=7, post_id=39)
  like40 = Comment(user_id=8, post_id=40)
  
  

  db.session.add(like1)
  db.session.add(like2)
  db.session.add(like3)
  db.session.add(like4)
  db.session.add(like5)
  db.session.add(like6)
  db.session.add(like7)
  db.session.add(like8)
  db.session.add(like9)
  db.session.add(like10)
  db.session.add(like11)
  db.session.add(like12)
  db.session.add(like13)
  db.session.add(like14)
  db.session.add(like15)
  db.session.add(like16)
  db.session.add(like17)
  db.session.add(like18)
  db.session.add(like19)
  db.session.add(like20)
  db.session.add(like21)
  db.session.add(like22)
  db.session.add(like23)
  db.session.add(like24)
  db.session.add(like25)
  db.session.add(like26)
  db.session.add(like27)
  db.session.add(like28)
  db.session.add(like29)
  db.session.add(like30)
  db.session.add(like31)
  db.session.add(like32)
  db.session.add(like33)
  db.session.add(like34)
  db.session.add(like35)
  db.session.add(like36)
  db.session.add(like37)
  db.session.add(like38)
  db.session.add(like39)
  db.session.add(like40)


  db.session.commit()


def undo_comments():
  # this restarts everything that has been added
  db.session.execute('TRUNCATE likes RESTART IDENTITY CASCADE;')
  db.session.commit()
